version: "3"

services:
  cache:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=petstore
  pgadmin: # https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html
    image: dpage/pgadmin4
    ports:
      - "9999:80"
    volumes:
      - type: bind
        source: ./servers.json
        target: /pgadmin4/servers.json
    environment:
      - PGADMIN_DEFAULT_EMAIL=curuvija@live.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
      - PGADMIN_SERVER_JSON_FILE=/pgadmin4/servers.json
  liquibase:
     image: liquibase/liquibase
     container_name: liquibase
     depends_on:
      - db
     hostname: liquibase
     volumes:
        - ./src/main/resources/db/changelog/db.changelog-master.xml:/liquibase/changelog.xml
     command: --url=jdbc:postgresql://db:5432/petstore?user=admin&password=admin --changeLogFile=changelog.xml update